/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.node;

import k31.grc.analysis.*;

@SuppressWarnings("nls")
public final class TOperLt extends Token
{
    public TOperLt()
    {
        super.setText("<");
    }

    public TOperLt(int line, int pos)
    {
        super.setText("<");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOperLt(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperLt(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOperLt text.");
    }
}
