/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AArrayDim extends PArrayDim
{
    private TSepLbrack _sepLbrack_;
    private TInteger _integer_;
    private TSepRbrack _sepRbrack_;

    public AArrayDim()
    {
        // Constructor
    }

    public AArrayDim(
        @SuppressWarnings("hiding") TSepLbrack _sepLbrack_,
        @SuppressWarnings("hiding") TInteger _integer_,
        @SuppressWarnings("hiding") TSepRbrack _sepRbrack_)
    {
        // Constructor
        setSepLbrack(_sepLbrack_);

        setInteger(_integer_);

        setSepRbrack(_sepRbrack_);

    }

    @Override
    public Object clone()
    {
        return new AArrayDim(
            cloneNode(this._sepLbrack_),
            cloneNode(this._integer_),
            cloneNode(this._sepRbrack_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayDim(this);
    }

    public TSepLbrack getSepLbrack()
    {
        return this._sepLbrack_;
    }

    public void setSepLbrack(TSepLbrack node)
    {
        if(this._sepLbrack_ != null)
        {
            this._sepLbrack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepLbrack_ = node;
    }

    public TInteger getInteger()
    {
        return this._integer_;
    }

    public void setInteger(TInteger node)
    {
        if(this._integer_ != null)
        {
            this._integer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integer_ = node;
    }

    public TSepRbrack getSepRbrack()
    {
        return this._sepRbrack_;
    }

    public void setSepRbrack(TSepRbrack node)
    {
        if(this._sepRbrack_ != null)
        {
            this._sepRbrack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepRbrack_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sepLbrack_)
            + toString(this._integer_)
            + toString(this._sepRbrack_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sepLbrack_ == child)
        {
            this._sepLbrack_ = null;
            return;
        }

        if(this._integer_ == child)
        {
            this._integer_ = null;
            return;
        }

        if(this._sepRbrack_ == child)
        {
            this._sepRbrack_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sepLbrack_ == oldChild)
        {
            setSepLbrack((TSepLbrack) newChild);
            return;
        }

        if(this._integer_ == oldChild)
        {
            setInteger((TInteger) newChild);
            return;
        }

        if(this._sepRbrack_ == oldChild)
        {
            setSepRbrack((TSepRbrack) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
