/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AAssignStmt extends PAssignStmt
{
    private PLValue _lValue_;
    private TSepAssign _sepAssign_;
    private PExpression _expression_;
    private TSepSemi _sepSemi_;

    public AAssignStmt()
    {
        // Constructor
    }

    public AAssignStmt(
        @SuppressWarnings("hiding") PLValue _lValue_,
        @SuppressWarnings("hiding") TSepAssign _sepAssign_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TSepSemi _sepSemi_)
    {
        // Constructor
        setLValue(_lValue_);

        setSepAssign(_sepAssign_);

        setExpression(_expression_);

        setSepSemi(_sepSemi_);

    }

    @Override
    public Object clone()
    {
        return new AAssignStmt(
            cloneNode(this._lValue_),
            cloneNode(this._sepAssign_),
            cloneNode(this._expression_),
            cloneNode(this._sepSemi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignStmt(this);
    }

    public PLValue getLValue()
    {
        return this._lValue_;
    }

    public void setLValue(PLValue node)
    {
        if(this._lValue_ != null)
        {
            this._lValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lValue_ = node;
    }

    public TSepAssign getSepAssign()
    {
        return this._sepAssign_;
    }

    public void setSepAssign(TSepAssign node)
    {
        if(this._sepAssign_ != null)
        {
            this._sepAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepAssign_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TSepSemi getSepSemi()
    {
        return this._sepSemi_;
    }

    public void setSepSemi(TSepSemi node)
    {
        if(this._sepSemi_ != null)
        {
            this._sepSemi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepSemi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lValue_)
            + toString(this._sepAssign_)
            + toString(this._expression_)
            + toString(this._sepSemi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lValue_ == child)
        {
            this._lValue_ = null;
            return;
        }

        if(this._sepAssign_ == child)
        {
            this._sepAssign_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._sepSemi_ == child)
        {
            this._sepSemi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lValue_ == oldChild)
        {
            setLValue((PLValue) newChild);
            return;
        }

        if(this._sepAssign_ == oldChild)
        {
            setSepAssign((TSepAssign) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._sepSemi_ == oldChild)
        {
            setSepSemi((TSepSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
