/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class ACharDataType extends PDataType
{
    private TKeyChar _keyChar_;

    public ACharDataType()
    {
        // Constructor
    }

    public ACharDataType(
        @SuppressWarnings("hiding") TKeyChar _keyChar_)
    {
        // Constructor
        setKeyChar(_keyChar_);

    }

    @Override
    public Object clone()
    {
        return new ACharDataType(
            cloneNode(this._keyChar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACharDataType(this);
    }

    public TKeyChar getKeyChar()
    {
        return this._keyChar_;
    }

    public void setKeyChar(TKeyChar node)
    {
        if(this._keyChar_ != null)
        {
            this._keyChar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keyChar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keyChar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keyChar_ == child)
        {
            this._keyChar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keyChar_ == oldChild)
        {
            setKeyChar((TKeyChar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
