/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AFactorLTermL extends PTermL
{
    private PFactorL _factorL_;

    public AFactorLTermL()
    {
        // Constructor
    }

    public AFactorLTermL(
        @SuppressWarnings("hiding") PFactorL _factorL_)
    {
        // Constructor
        setFactorL(_factorL_);

    }

    @Override
    public Object clone()
    {
        return new AFactorLTermL(
            cloneNode(this._factorL_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFactorLTermL(this);
    }

    public PFactorL getFactorL()
    {
        return this._factorL_;
    }

    public void setFactorL(PFactorL node)
    {
        if(this._factorL_ != null)
        {
            this._factorL_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factorL_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factorL_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factorL_ == child)
        {
            this._factorL_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factorL_ == oldChild)
        {
            setFactorL((PFactorL) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
