/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import java.util.*;
import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AFparType extends PFparType
{
    private PDataType _dataType_;
    private PArrayNoDim _arrayNoDim_;
    private final LinkedList<PArrayDim> _arrayDim_ = new LinkedList<PArrayDim>();

    public AFparType()
    {
        // Constructor
    }

    public AFparType(
        @SuppressWarnings("hiding") PDataType _dataType_,
        @SuppressWarnings("hiding") PArrayNoDim _arrayNoDim_,
        @SuppressWarnings("hiding") List<?> _arrayDim_)
    {
        // Constructor
        setDataType(_dataType_);

        setArrayNoDim(_arrayNoDim_);

        setArrayDim(_arrayDim_);

    }

    @Override
    public Object clone()
    {
        return new AFparType(
            cloneNode(this._dataType_),
            cloneNode(this._arrayNoDim_),
            cloneList(this._arrayDim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFparType(this);
    }

    public PDataType getDataType()
    {
        return this._dataType_;
    }

    public void setDataType(PDataType node)
    {
        if(this._dataType_ != null)
        {
            this._dataType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dataType_ = node;
    }

    public PArrayNoDim getArrayNoDim()
    {
        return this._arrayNoDim_;
    }

    public void setArrayNoDim(PArrayNoDim node)
    {
        if(this._arrayNoDim_ != null)
        {
            this._arrayNoDim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayNoDim_ = node;
    }

    public LinkedList<PArrayDim> getArrayDim()
    {
        return this._arrayDim_;
    }

    public void setArrayDim(List<?> list)
    {
        for(PArrayDim e : this._arrayDim_)
        {
            e.parent(null);
        }
        this._arrayDim_.clear();

        for(Object obj_e : list)
        {
            PArrayDim e = (PArrayDim) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._arrayDim_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dataType_)
            + toString(this._arrayNoDim_)
            + toString(this._arrayDim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dataType_ == child)
        {
            this._dataType_ = null;
            return;
        }

        if(this._arrayNoDim_ == child)
        {
            this._arrayNoDim_ = null;
            return;
        }

        if(this._arrayDim_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dataType_ == oldChild)
        {
            setDataType((PDataType) newChild);
            return;
        }

        if(this._arrayNoDim_ == oldChild)
        {
            setArrayNoDim((PArrayNoDim) newChild);
            return;
        }

        for(ListIterator<PArrayDim> i = this._arrayDim_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PArrayDim) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
