/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AFunctionArgsMore extends PFunctionArgsMore
{
    private TSepComma _sepComma_;
    private PExpression _expression_;

    public AFunctionArgsMore()
    {
        // Constructor
    }

    public AFunctionArgsMore(
        @SuppressWarnings("hiding") TSepComma _sepComma_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setSepComma(_sepComma_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionArgsMore(
            cloneNode(this._sepComma_),
            cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionArgsMore(this);
    }

    public TSepComma getSepComma()
    {
        return this._sepComma_;
    }

    public void setSepComma(TSepComma node)
    {
        if(this._sepComma_ != null)
        {
            this._sepComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepComma_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sepComma_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sepComma_ == child)
        {
            this._sepComma_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sepComma_ == oldChild)
        {
            setSepComma((TSepComma) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
