/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AFunctionCall extends PFunctionCall
{
    private TIdentifier _identifier_;
    private TSepLpar _sepLpar_;
    private PFunctionArgs _functionArgs_;
    private TSepRpar _sepRpar_;

    public AFunctionCall()
    {
        // Constructor
    }

    public AFunctionCall(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") TSepLpar _sepLpar_,
        @SuppressWarnings("hiding") PFunctionArgs _functionArgs_,
        @SuppressWarnings("hiding") TSepRpar _sepRpar_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setSepLpar(_sepLpar_);

        setFunctionArgs(_functionArgs_);

        setSepRpar(_sepRpar_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionCall(
            cloneNode(this._identifier_),
            cloneNode(this._sepLpar_),
            cloneNode(this._functionArgs_),
            cloneNode(this._sepRpar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionCall(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public TSepLpar getSepLpar()
    {
        return this._sepLpar_;
    }

    public void setSepLpar(TSepLpar node)
    {
        if(this._sepLpar_ != null)
        {
            this._sepLpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepLpar_ = node;
    }

    public PFunctionArgs getFunctionArgs()
    {
        return this._functionArgs_;
    }

    public void setFunctionArgs(PFunctionArgs node)
    {
        if(this._functionArgs_ != null)
        {
            this._functionArgs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionArgs_ = node;
    }

    public TSepRpar getSepRpar()
    {
        return this._sepRpar_;
    }

    public void setSepRpar(TSepRpar node)
    {
        if(this._sepRpar_ != null)
        {
            this._sepRpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepRpar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._sepLpar_)
            + toString(this._functionArgs_)
            + toString(this._sepRpar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._sepLpar_ == child)
        {
            this._sepLpar_ = null;
            return;
        }

        if(this._functionArgs_ == child)
        {
            this._functionArgs_ = null;
            return;
        }

        if(this._sepRpar_ == child)
        {
            this._sepRpar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._sepLpar_ == oldChild)
        {
            setSepLpar((TSepLpar) newChild);
            return;
        }

        if(this._functionArgs_ == oldChild)
        {
            setFunctionArgs((PFunctionArgs) newChild);
            return;
        }

        if(this._sepRpar_ == oldChild)
        {
            setSepRpar((TSepRpar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
