/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AIntDataType extends PDataType
{
    private TKeyInt _keyInt_;

    public AIntDataType()
    {
        // Constructor
    }

    public AIntDataType(
        @SuppressWarnings("hiding") TKeyInt _keyInt_)
    {
        // Constructor
        setKeyInt(_keyInt_);

    }

    @Override
    public Object clone()
    {
        return new AIntDataType(
            cloneNode(this._keyInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntDataType(this);
    }

    public TKeyInt getKeyInt()
    {
        return this._keyInt_;
    }

    public void setKeyInt(TKeyInt node)
    {
        if(this._keyInt_ != null)
        {
            this._keyInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keyInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keyInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keyInt_ == child)
        {
            this._keyInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keyInt_ == oldChild)
        {
            setKeyInt((TKeyInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
