/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class ANothingReturnType extends PReturnType
{
    private TKeyNothing _keyNothing_;

    public ANothingReturnType()
    {
        // Constructor
    }

    public ANothingReturnType(
        @SuppressWarnings("hiding") TKeyNothing _keyNothing_)
    {
        // Constructor
        setKeyNothing(_keyNothing_);

    }

    @Override
    public Object clone()
    {
        return new ANothingReturnType(
            cloneNode(this._keyNothing_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANothingReturnType(this);
    }

    public TKeyNothing getKeyNothing()
    {
        return this._keyNothing_;
    }

    public void setKeyNothing(TKeyNothing node)
    {
        if(this._keyNothing_ != null)
        {
            this._keyNothing_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keyNothing_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keyNothing_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keyNothing_ == child)
        {
            this._keyNothing_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keyNothing_ == oldChild)
        {
            setKeyNothing((TKeyNothing) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
