/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AReturnStmt extends PReturnStmt
{
    private TKeyReturn _keyReturn_;
    private PExpression _expression_;
    private TSepSemi _sepSemi_;

    public AReturnStmt()
    {
        // Constructor
    }

    public AReturnStmt(
        @SuppressWarnings("hiding") TKeyReturn _keyReturn_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TSepSemi _sepSemi_)
    {
        // Constructor
        setKeyReturn(_keyReturn_);

        setExpression(_expression_);

        setSepSemi(_sepSemi_);

    }

    @Override
    public Object clone()
    {
        return new AReturnStmt(
            cloneNode(this._keyReturn_),
            cloneNode(this._expression_),
            cloneNode(this._sepSemi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReturnStmt(this);
    }

    public TKeyReturn getKeyReturn()
    {
        return this._keyReturn_;
    }

    public void setKeyReturn(TKeyReturn node)
    {
        if(this._keyReturn_ != null)
        {
            this._keyReturn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keyReturn_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TSepSemi getSepSemi()
    {
        return this._sepSemi_;
    }

    public void setSepSemi(TSepSemi node)
    {
        if(this._sepSemi_ != null)
        {
            this._sepSemi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepSemi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keyReturn_)
            + toString(this._expression_)
            + toString(this._sepSemi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keyReturn_ == child)
        {
            this._keyReturn_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._sepSemi_ == child)
        {
            this._sepSemi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keyReturn_ == oldChild)
        {
            setKeyReturn((TKeyReturn) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._sepSemi_ == oldChild)
        {
            setSepSemi((TSepSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
