/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class TOperMod extends Token
{
    public TOperMod()
    {
        super.setText("mod");
    }

    public TOperMod(int line, int pos)
    {
        super.setText("mod");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOperMod(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperMod(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOperMod text.");
    }
}
