/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class TOperNot extends Token
{
    public TOperNot()
    {
        super.setText("not");
    }

    public TOperNot(int line, int pos)
    {
        super.setText("not");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOperNot(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperNot(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOperNot text.");
    }
}
