/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class TSepAssign extends Token
{
    public TSepAssign()
    {
        super.setText("<-");
    }

    public TSepAssign(int line, int pos)
    {
        super.setText("<-");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSepAssign(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSepAssign(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSepAssign text.");
    }
}
