#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "${DIR}"/grc.cfg

[ ! -x "${GRC}" ] && ("${DIR}"/build.sh; echo)

if [ ${ENV} = 'DotNet' ]
then
	"${GRC}" $*
elif [ ${ENV} = 'Mono' ]
then
	mono "${GRC}" $*
fi

