/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class ABlockStatement extends PStatement
{
    private PBlockStmt _blockStmt_;

    public ABlockStatement()
    {
        // Constructor
    }

    public ABlockStatement(
        @SuppressWarnings("hiding") PBlockStmt _blockStmt_)
    {
        // Constructor
        setBlockStmt(_blockStmt_);

    }

    @Override
    public Object clone()
    {
        return new ABlockStatement(
            cloneNode(this._blockStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockStatement(this);
    }

    public PBlockStmt getBlockStmt()
    {
        return this._blockStmt_;
    }

    public void setBlockStmt(PBlockStmt node)
    {
        if(this._blockStmt_ != null)
        {
            this._blockStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blockStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blockStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blockStmt_ == child)
        {
            this._blockStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blockStmt_ == oldChild)
        {
            setBlockStmt((PBlockStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
