/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import java.util.*;
import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AFunctionArgs extends PFunctionArgs
{
    private PExpression _expression_;
    private final LinkedList<PFunctionArgsMore> _functionArgsMore_ = new LinkedList<PFunctionArgsMore>();

    public AFunctionArgs()
    {
        // Constructor
    }

    public AFunctionArgs(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<?> _functionArgsMore_)
    {
        // Constructor
        setExpression(_expression_);

        setFunctionArgsMore(_functionArgsMore_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionArgs(
            cloneNode(this._expression_),
            cloneList(this._functionArgsMore_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionArgs(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PFunctionArgsMore> getFunctionArgsMore()
    {
        return this._functionArgsMore_;
    }

    public void setFunctionArgsMore(List<?> list)
    {
        for(PFunctionArgsMore e : this._functionArgsMore_)
        {
            e.parent(null);
        }
        this._functionArgsMore_.clear();

        for(Object obj_e : list)
        {
            PFunctionArgsMore e = (PFunctionArgsMore) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._functionArgsMore_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._functionArgsMore_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._functionArgsMore_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PFunctionArgsMore> i = this._functionArgsMore_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFunctionArgsMore) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
