/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class ATermLExpressionL extends PExpressionL
{
    private PTermL _termL_;

    public ATermLExpressionL()
    {
        // Constructor
    }

    public ATermLExpressionL(
        @SuppressWarnings("hiding") PTermL _termL_)
    {
        // Constructor
        setTermL(_termL_);

    }

    @Override
    public Object clone()
    {
        return new ATermLExpressionL(
            cloneNode(this._termL_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermLExpressionL(this);
    }

    public PTermL getTermL()
    {
        return this._termL_;
    }

    public void setTermL(PTermL node)
    {
        if(this._termL_ != null)
        {
            this._termL_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termL_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termL_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termL_ == child)
        {
            this._termL_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termL_ == oldChild)
        {
            setTermL((PTermL) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
