/* This file was generated by SableCC (http://www.sablecc.org/). */

package k31.grc.cst.node;

import k31.grc.cst.analysis.*;

@SuppressWarnings("nls")
public final class AWhileStatementElse extends PStatementElse
{
    private PWhileStmtElse _whileStmtElse_;

    public AWhileStatementElse()
    {
        // Constructor
    }

    public AWhileStatementElse(
        @SuppressWarnings("hiding") PWhileStmtElse _whileStmtElse_)
    {
        // Constructor
        setWhileStmtElse(_whileStmtElse_);

    }

    @Override
    public Object clone()
    {
        return new AWhileStatementElse(
            cloneNode(this._whileStmtElse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileStatementElse(this);
    }

    public PWhileStmtElse getWhileStmtElse()
    {
        return this._whileStmtElse_;
    }

    public void setWhileStmtElse(PWhileStmtElse node)
    {
        if(this._whileStmtElse_ != null)
        {
            this._whileStmtElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whileStmtElse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whileStmtElse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whileStmtElse_ == child)
        {
            this._whileStmtElse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whileStmtElse_ == oldChild)
        {
            setWhileStmtElse((PWhileStmtElse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
